# MovieLens, Amazon
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
    inter: [user_id, item_id, rating, timestamp]

NEG_PREFIX: neg_
LABEL_FIELD: label
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id

#max_user_inter_num: 100
min_user_inter_num: 5
#max_item_inter_num: 100
min_item_inter_num: 5

# training settings
epochs: 30
stopping_step: 40
embedding_dim: 64
hidden_size: 64
train_batch_size: 256
learner: adam
learning_rate: 0.001
training_neg_sample_num: 0
eval_step: 1
# evalution settings
eval_setting: TO_LS,full
metrics: ["Recall","MRR","NDCG","Hit","precision"]
valid_metric: NDCG@10
eval_batch_size: 256
weight_decay: 0
topk: [5, 10]

#split_ratio: [0.6,0.2,0.2]
# directory setting
log_root: "./log/"
data_path: "./datasets/"
#checkpoint_dir:

lmd: 0.3
#lmd_sem: 0.1

tau: 1

# choose from {un, su, us, us_x}
contrast: 'us_x'

# choose from {dot, cos}
sim: 'dot'

hidden_dropout_prob: 0.3
attn_dropout_prob: 0.3

loss_type : 'CE'

train_r : 1

noise : 'CLOSE'

noise_r : 0

same_length : 10
